### ISSUE TITLE
Pasar al reporte las correcciones que mandó el profesor por Canvas

### ISSUE THREAD

**Issue by kennyldc** [kennyldc/proyecto_final_opt21_eq8#19]

**Comment by Fminaurol** [comment]
Ya agregué la respuesta a la pregunta del profesor de: ¿pueden añadir un print que muestre el porcentaje de varianza acumulada? Además, agregué el comentario para que se observe la descomposición que tiene cada componente principal

**Comment by kennyldc** [comment]
Gracias @Fminaurol, noté que @Juanes8 planteó el problema de optimización por lo que cerraré este issue.
